#!/usr/bin/env ansible-playbook
- name: SAVE CONFIGURATION
  hosts: all
  gather_facts: false
  tasks:
    - name: SAVING CONFIGURATION WITH cli_command
      ansible.netcommon.cli_command:
        command: copy running-config startup-config
        check_all: true
        prompt:
          - Destination filename
        answer:
          - startup-config
