#!/usr/bin/env ansible-playbook
- name: CLEAR INTERFACE COUNTERS
  hosts: all
  gather_facts: false
  tasks:
    - name: CLEARING INTERFACE COUNTERS WITH ios_command
      cisco.ios.ios_command:
        commands:
          - command: clear counters
            prompt: Clear "show interface" counters on all interfaces
            answer: y
