#!/usr/bin/env ansible-playbook
- name: CLEAR INTERFACE COUNTERS
  hosts: all
  gather_facts: false
  tasks:
    - name: CLEARING INTERFACE COUNTERS WITH cli_command
      ansible.netcommon.cli_command:
        command: clear counters
        check_all: true
        prompt:
          - Clear "show interface" counters on all interfaces
        answer:
          - y
