apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx.yaml
