# Manually run with:
#   - source venv/bin/activate
#   - pre-commit install
#   - pre-commit run --all-files
# See https://pre-commit.com/hooks.html for more hooks
exclude: \.raw|migrations|docker|.venv|venv|playbook-with-errors.yml|templates|old|files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: check-yaml
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, .bandit.yml]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.4
    hooks:
      - id: remove-tabs
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: ansible-navigator-lint
        name: ansible-navigator lint
        entry: venv/bin/ansible-navigator --ee=false lint -m stdout Ansible
        language: script
        pass_filenames: false
      - id: ansible-lint
        name: ansible-lint
        entry: venv/bin/ansible-lint Ansible
        language: script
        pass_filenames: false
