# See:
# - https://ansible.readthedocs.io/projects/builder/en/latest/definition/
# - https://www.linkedin.com/pulse/creating-custom-ee-awx-phil-griffiths/
version: 3
dependencies:
  system: dependencies/bindep.txt
  python: dependencies/requirements.txt
  galaxy: dependencies/requirements.yml
images:
  base_image:
    name: quay.io/ansible/awx-ee:24.3.1
additional_build_steps:
  prepend_base:
    - RUN echo "Additional steps for prepend_base"
  append_base:
    - RUN echo "Additional steps for append_base"
  prepend_galaxy:
    - RUN echo "Additional steps for prepend_galaxy"
