#!/usr/bin/env ansible-playbook
- name: CONFIGURE FABRIC
  hosts: core,access
  gather_facts: false
  roles:
    - role: cisco_ios_system
      tags: dns,hostname
    - role: cisco_ios_ntp
      tags: ntp
    - role: cisco_ios_snmpv2
      tags: snmp
    - role: cisco_ios_vlan
      tags: vlan
    - role: cisco_ios_interface_profile
      tags: interface
  pre_tasks:
    - name: CHECKING BASTION HOST
      when: ansible_ssh_common_args is defined
      block:
        - name: BASTION HOST CONFIGURATION
          ansible.builtin.debug:
            msg: "ansible_ssh_common_args: {{ ansible_ssh_common_args }}"
        - name: CHECKING SSH KEY
          delegate_to: localhost
          ansible.builtin.stat:
            path: /opt/bastionhost_id_rsa
          register: ssh_key
        - name: FAIL IF SSH KEY IS MISSINT
          ansible.builtin.fail:
            msg: "/opt/bastionhost_id_rsa is missing"
          when: not ssh_key.stat.exists
    - delegate_to: localhost
      command:
        cmd: ls -l /opt
      register: aaa
    - debug:
        msg: "{{ aaa }}"
    - debug:
        msg: "{{ ssh_key }}"
      
      
  post_tasks:
    - name: SAVING CONFIG
      tags: always
      cisco.ios.ios_config:
        save_when: modified
