#!/usr/bin/env ansible-playbook
- name: CONFIGURE FABRIC
  hosts: core,access
  gather_facts: false
  roles:
    - role: cisco_ios_system
      tags: dns,hostname
    - role: cisco_ios_ntp
      tags: ntp
    - role: cisco_ios_snmpv2
      tags: snmp
    - role: cisco_ios_vlan
      tags: vlan
    - role: cisco_ios_interface_profile
      tags: interface
  pre_tasks:
    - name: CHECKING BASTION HOST
      when: ansible_ssh_common_args is defined
      run_once: true
      block:
        - name: BASTION HOST CONFIGURATION
          ansible.builtin.debug:
            msg: "ansible_ssh_common_args: {{ ansible_ssh_common_args }}"
        - name: CHECKING SSH KEY
          delegate_to: localhost
          ansible.builtin.stat:
            path: /opt/bastionhost_id_rsa
          register: ssh_key
        - name: FAIL IF SSH KEY IS MISSING
          ansible.builtin.fail:
            msg: "/opt/bastionhost_id_rsa is missing"
          when: not ssh_key.stat.exists
        - name: CHECKING PERMISSIONS
          delegate_to: localhost
          ansible.builtin.command:
            cmd: ls -al /opt /opt/bastionhost_id_rsa/ /opt/bastionhost_id_rsa/ssh-privatekey
          register: ssh_key_permissions
        - name: LISTING SSH KEY PERMISSIONS
          ansible.builtin.debug:
            msg: "{{ ssh_key_permissions.stdout_lines }}"
        # - command:
        #     cmd: cat /opt/ssh-privatekey
        #   register: a
        # - debug:
        #     msg: "{{ a }}"

  post_tasks:
    - name: SAVING CONFIG
      tags: always
      cisco.ios.ios_config:
        save_when: modified
