#!/usr/bin/env ansible-playbook
- name: CLEAR COUNTERS
  hosts: all
  gather_facts: false
  tasks:
    - name: CLEAR COUNTERS WITH cli_command
      ansible.netcommon.cli_command:
        command: clear counters
        check_all: true
        prompt:
          - Clear "show interface" counters on all interfaces
        answer:
          - y
    - name: CLEAR COUNTERS WITH ios_command
      cisco.ios.ios_command:
        commands:
          - command: clear counters
            prompt: Clear "show interface" counters on all interfaces
            answer: y
    - name: CONFIGURATION SAVE WITH cli_command
      ansible.netcommon.cli_command:
        command: copy running-config startup-config
        check_all: true
        prompt:
          - Destination filename
        answer:
          - startup-config
    - name: CONFIGURATION SAVE WITH ios_command
      cisco.ios.ios_command:
        commands:
          - command: copy running-config startup-config
            prompt: Destination filename
            answer: startup-config
