#!/usr/bin/env ansible-playbook
- name: PARSERS
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: GETTING OUTPUT
      ansible.builtin.command:
        cmd: uname -a
      register: output
    - name: PRINTING PARSED OUTPUT
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines[0] | community.general.jc('uname') }}"
