#!/usr/bin/env ansible-playbook
- name: CUSTOM FILTERS
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: SETTING VARIABLES
      ansible.builtin.set_fact:
        text: "AI will rule the world!"
        items_list:
          - key: a
            value: item1
          - key: b
            value: item2
          - key: c
            value: item3
    - name: PRINTING CUSTOM TEXT
      ansible.builtin.debug:
        msg: "{{ text | real_ai_name }}"
    - name: PRINTING CUSTOM DICT
      ansible.builtin.debug:
        msg: "{{ items_list | to_dict('key') }}"
