#!/usr/bin/env ansible-playbook
- name: SYSTEM CONFIGURATION
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: SETTING BASTION HOST VARIABLES
      ansible.builtin.set_fact:
        bastion_user: ansible
        bastion_host: 172.25.82.110
        bastion_ssh_private_key_file: ~/.ssh/id_rsa
    - name: ENABLING BASTION HOST FOR SSH USAGE
      ansible.builtin.set_fact:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh
          -o IdentityFile={{ bastion_ssh_private_key_file }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -W %h:%p
          -q {{ bastion_user }}@{{ bastion_host }}"
  tasks:
    - name: CONFIGURING FQDN
      tags: system,fqdn
      cisco.ios.ios_system:
        hostname: "{{ inventory_hostname_short }}"
        domain_name: "example.com"
