#!/usr/bin/env ansible-playbook
- name: PRINT DEBUG VARIABLES
  hosts: all
  gather_facts: true
  connection: local
  tasks:
    - name: PRINT MODULE VARIABLES (vars)
      vars:
        msg: |
          -------------------------------------------------------------------------
          {{ vars | to_nice_json }}
          -------------------------------------------------------------------------
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: vars
    - name: PRINT ENVIRONMENT VARIABLES (environment)
      vars:
        msg: |
          -------------------------------------------------------------------------
          {{ environment | to_nice_json }}
          -------------------------------------------------------------------------
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: environment
    - name: PRINT GROUP NAMES VARIABLES (group_names)
      vars:
        msg: |
          -------------------------------------------------------------------------
          {{ group_names | to_nice_json }}
          -------------------------------------------------------------------------
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: group_names
    - name: PRINT GROUPS VARIABLES (groups)
      vars:
        msg: |
          -------------------------------------------------------------------------
          {{ groups | to_nice_json }}
          -------------------------------------------------------------------------
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: groups
    - name: PRINT HOST VARIABLES (hostvars)
      vars:
        msg: |
          -------------------------------------------------------------------------
          {{ hostvars | to_nice_json }}
          -------------------------------------------------------------------------
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: hostvars
