# tasks file for roles/cisco_ios_uplink_interface
# Configure upstream interface
- name: "CONFIGURING UPSTREAM SW1"
  delegate_to: sw1.example.com
  cisco.ios.ios_config:
    lines:
      - "description to {{ inventory_hostname }}"
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport nonegotiate
      - udld port aggressive
    parents: "interface {{ upstream_interface }}"
    before: "default interface {{ upstream_interface }}"
- name: "CONFIGURING UPSTREAM SW2"
  delegate_to: sw2.example.com
  cisco.ios.ios_config:
    lines:
      - "description to {{ inventory_hostname }}"
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport nonegotiate
      - udld port aggressive
    parents: "interface {{ upstream_interface }}"
    before: "default interface {{ upstream_interface }}"
