# included tasks file for roles/cisco_ios_port_profile
# Configure profile client
- name: "APPLYING PROFILE OFFICE TO INTERFACE {{ interface.key }}"
  cisco.ios.ios_config:
    config: "{{ show_running_config.stdout.0 }}"
    lines:
      - switchport access vlan 53
      - no cdp enable
      - no lldp receive
      - no lldp transmit
      - spanning-tree bpduguard enable
      - spanning-tree portfast edge
      - switchport mode access
      - switchport nonegotiate
    parents: "interface {{ interface.key }}"
    before: "default interface {{ interface.key }}"
