- name: "LISTEN FOR EVENTS VIA SYSLOG"
  hosts: all
  sources:
    - dainok.courses.syslog:
        host: 0.0.0.0
        port: 1514
  rules:
    - name: "RUN PLAYBOOK WHEN ROUTER IS CONFIGURED"
      condition: event.message is match("Configured from.*", ignorecase=true)
      actions:
        - run_playbook:
            name: playbook-backup.yml
        - print_event:
            pretty: true

