- name: SETTING VARIABLES
  connection: local
  ansible.builtin.set_fact:
    var1: snake
    list1:
      - macos
      - windows
      - linux
    list2:
      - red
      - green
      - orange
    dict1:
      macos: apple
      windows: microsoft
      linux: opensource
# Simple loop example
- name: SIMPLE LOOP
  connection: local
  ansible.builtin.debug:
    msg: Now reading {{ item }}
  with_items: "{{ list1 }}"
# Simple dict example
- name: SIMPLE DICT
  connection: local
  ansible.builtin.debug:
    msg: Now reading {{ item.key }} by {{ item.value }}
  with_dict: "{{ dict1 }}"
# Nested loops example
- name: CALLING OUTER LOOP
  ansible.builtin.include_tasks: sub_task1.yml
  with_items: "{{ list1 }}"
  loop_control:
    loop_var: outer_item
