# Print parent variable
- name: PARENT VARIABLE
  connection: local
  ansible.builtin.debug:
    msg: Now reading {{ var1 }} from main
# Print loop variable
- name: OUTER LOOP VARIABLE
  connection: local
  ansible.builtin.debug:
    msg: Now reading {{ outer_item }} from outer loop
# Nested loops example
- name: CALLING MIDDLE LOOP
  ansible.builtin.include_tasks: sub_task2.yml
  with_items: "{{ list2 }}"
  loop_control:
    loop_var: inner_item
