#!/usr/bin/env ansible-playbook
- name: TTP PARSERS
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: PARSING
      ansible.utils.cli_parse:
        command: show ip arp
        parser:
          name: ansible.utils.ttp
          os: "cisco_ios"
        set_fact: output_parsed
    - name: PRINTING PARSED OUTPUT
      ansible.builtin.debug:
        msg: "{{ output_parsed }}"
