#!/usr/bin/env ansible-playbook
- name: TTP PARSERS
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: READING OUTPUT
      cisco.ios.ios_command:
        commands: show ip arp
      register: output
    - name: PARSING
      ansible.utils.cli_parse:
        text: "{{ output['stdout'][0] }}"
        parser:
          name: ansible.utils.ttp
          os: "cisco_ios"
          command: "show ip arp"
        set_fact: output_parsed
    - name: PRINTING PARSED OUTPUT
      ansible.builtin.debug:
        msg: "{{ output_parsed }}"
