#!/usr/bin/env ansible-playbook
- name: PYATS PARSER
  hosts: all
  gather_facts: false
  tasks:
    - name: PARSING
      ansible.utils.cli_parse:
        command: "show ip interface brief"
        parser:
          name: ansible.netcommon.pyats
        set_fact: output_parsed
    - name: PRINTING PARSED OUTPUT
      ansible.builtin.debug:
        msg: "{{ output_parsed }}"
