# included tasks file for roles/cisco_ios_port_profile
# Configure profile hypervisor
- name: "APPLYING PROFILE HYPERVISOR TO INTERFACE {{ interface.key }}"
  cisco.ios.ios_config:
    config: "{{ show_running_config.stdout.0 }}"
    lines:
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport nonegotiate
      - spanning-tree bpduguard enable
      - spanning-tree portfast edge trunk
      - udld port aggressive
    parents: "interface {{ interface.key }}"
    before: "default interface {{ interface.key }}"
