#!/usr/bin/env ansible-playbook
- name: CONFIGURE FABRIC
  hosts: core,access
  gather_facts: false
  roles:
    - role: cisco_ios_system
      tags: dns,hostname
    - role: cisco_ios_ntp
      tags: ntp
    - role: cisco_ios_snmpv2
      tags: snmp
    - role: cisco_ios_vlan
      tags: vlan
    - role: cisco_ios_interface_profile
      tags: interface
  post_tasks:
    - name: SAVING CONFIG
      tags: always
      cisco.ios.ios_config:
        save_when: modified
