misp:
  url: https://172.24.1.18/
  verify_cert: False
  timeout: 5
event:
  title: Suspicious email
  org: ORGNAME
  distribution: 2  # Connected communities
  threat_level: 4  # Undefined
export:
  last_days: 180
  last_ioc: 5000
  port: 8080
imap:
  url: imap.gmail.com
