# Generate TSF
- name: GENERATING TSF
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: request tech-support dump
  register: tsf_dump
# Wait for job copletition
- name: CHECKING TSF RESULT
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: "show jobs id {{ (tsf_dump.stdout | from_json).response.result.job }}"
  register: tsf_dump_check
  until: tsf_dump_check is not failed and (tsf_dump_check.stdout | from_json).response.result.job.status == "FIN"
  retries: 15
  delay: 60
# Download TSF
- name: DOWNLOADING TSF
  ansible.builtin.get_url:
    url: "https://{{ provider.ip_address }}/api/?key={{ provider.api_key }}&type=export&category=tech-support&action=get&job-id={{ (tsf_dump.stdout | from_json).response.result.job }}"
    validate_certs: false
    dest: "./tsf-{{ provider.ip_address }}-{{ now(utc=true,fmt='%Y%m%d%H%M%S') }}.tar.gz"
    mode: '0644'
