all:
  hosts:
    sw1.example.com:
      ansible_host: 169.254.1.101
      role: core
    sw2.example.com:
      ansible_host: 169.254.1.102
      role: core
    sw3.example.com:
      ansible_host: 169.254.1.103
      role: access
    sw4.example.com:
      ansible_host: 169.254.1.104
      role: access
    sw5.example.com:
      ansible_host: 169.254.1.105
      role: access
    sw6.example.com:
      ansible_host: 169.254.1.106
      role: access
  vars:
    group_all_var: value
  children:
    cisco_ios:
      hosts:
        sw1.example.com:
        sw2.example.com:
        sw3.example.com:
        sw4.example.com:
        sw5.example.com:
        sw6.example.com:
      vars:
        ansible_user: admin
        ansible_password: cisco
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
