#!/usr/bin/env ansible-playbook
- name: ROUTER CONFIGURATION
  hosts: all
  gather_facts: false
  vars_files:
    - config.yml
  roles:
    - role: cisco-ios-ntp
      tags: ntp
    - role: cisco-ios-ntp-raw
      tags: ntp_raw
    - role: cisco-ios-config-save
      tags: always,save
  pre_tasks:
    - name: SETTING BASTION HOST VARIABLES
      tags: always
      ansible.builtin.set_fact:
        bastion_user: ansible
        bastion_host: 172.25.82.110
        bastion_ssh_private_key_file: ~/.ssh/id_rsa
    - name: ENABLING BASTION HOST FOR SSH USAGE
      tags: always
      ansible.builtin.set_fact:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh
          -o IdentityFile={{ bastion_ssh_private_key_file }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -W %h:%p
          -q {{ bastion_user }}@{{ bastion_host }}"
    - name: GETTING RUNNING CONFIG
      tags: always
      cisco.ios.ios_command:
        commands: show running-config
      register: show_running_config_output
    - name: EXTRACTING RUNNING CONFIG
      tags: always
      ansible.builtin.set_fact:
        running_config: "{{ show_running_config_output.stdout[0] }}"
